sass:
  sass_dir: _sass

future: true

algolia:
  application_id: 'FL9GO11HZ6'
  index_name: 'Depressed_traveller'
  search_only_api_key: 3e7d65dbef7e7a30e38f11111b6a2dc5
  files_to_exclude:
    - index.html
    - searchAll.html
    - category/china.html
    - /searchAll/searchAll.html
settings:
    highlightPreTag: '<em class="custom_highlight">'
    highlightPostTag: '</em>'

baseurl: 'https://martagut.github.io/Antiblog/'
url: 'https://github.com/MartaGut.io'

github: [metadata]

repository: 'MartaGut/Antiblog'

localhost: 'http://127.0.0.1:4000'

tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_permalink_style: pretty

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"